angular-ui/bootstrap

src/modal/modal.js
template/modal/window.html

This change attempts to fix issue #2280 
ng-click directive has been removed from modal template and click event moved to the modal-window directive code, so the click event keeps firing and modal window closes when clicking on the backdrop. Not sure if there's a better place to put this event but the fix seems to be working.

fix(modal): fix for conflicts with ngTouch module on mobile devices

---

src/tooltip/tooltip.js

Tooltip on button doesn't hide if button is disabled on click. Fix for issue #3167

fix(tooltip): Fix for issue #3167

---

src/accordion/accordion.js
src/accordion/test/accordion.spec.js
src/collapse/collapse.js
template/accordion/accordion-group.html

~~Update: Most likely going to change this approach to something similar to what I did for #1772.~~
~~Not ready yet until carousel is fixed with ngAnimate as ngAnimate breaks carousel.~~
- Deprecate collapse module
Consider removing the collapse module after transition module is deprecated as well.
@pkozlowski-opensource , the way I see it, ngAnimate makes animations coupled with the template. I think this makes sense as it's a layer of presentation logic. As such, perhaps having class names only in animations (and templates) might be okay.
TODO:
- ~~Update when https://github.com/angular/angular.js/pull/5984 is updated~~

refactor(accordion): use ngAnimate for animations

---

src/modal/modal.js
src/modal/test/modal.spec.js

Supercedes #1772 
This makes use of the new `$animate:close` event to determine that the animation is done instead of using `$transition`. There are minimal changes to the current code and there's one fix and the removal of some timers.

refactor(modal): use ngAnimate for animation

---

src/accordion/accordion.js
src/accordion/test/accordion.spec.js
src/collapse/collapse.js
src/collapse/test/collapse.spec.js
template/accordion/accordion-group.html

Update: After merging #1675, I realized most of that logic can now be moved into collapse, as AngularJS 1.3 supports style options on animation calls. I've refactored it so that accordion and collapse share the same logic.
This is my attempt at #1274 .

refactor(collapse): use ngAnimate

---

template/timepicker/timepicker.html

The timepicker template has an ng-mousewheel
binding on the hours input element and the
TimepickerController also binds the elemeent
to mouse wheel events.  Removed ng-mousewheel
binding from the template.

fix(timepicker): remove ng-mousewheel binding

---

src/tooltip/test/tooltip.spec.js
src/tooltip/tooltip.js

Reposition on each digest, this ensures that the tooltip is always positioned
correctly no matter how its content changes.
Fixes #96
Fixes #1109
Closes #2816
Prerequisite of #1848

feat(tooltip): update position dynamically

---

src/popover/docs/demo.html
src/popover/docs/demo.js
src/popover/docs/readme.md
src/popover/popover.js
src/popover/test/popover-template.spec.js
src/tooltip/docs/demo.html
src/tooltip/docs/readme.md
src/tooltip/test/tooltip-template.spec.js
src/tooltip/tooltip.js
template/popover/popover-template.html
template/tooltip/tooltip-template-popup.html

**Update: This is ready to merge.**
~~Here's a poll for anybody to get involved in voting to name this directive:
http://goo.gl/forms/oxW1B4L81B~~ Thank you. It'll be called `popover-template` and `tooltip-template`.
Update: I finally got to this. This should be ready for testing.
TODO:
This is a proof of concept to use a tooltipController to transclude a template.
It's based off #1600 and most of the changes are from that. See https://github.com/chrisirhc/angular-ui-bootstrap/commit/0a1510c957bd385db61dcb1a8366fef97fd38e74 for actual changes for the popoverWindow.
Tests are missing but I wanted to open this up for discussion or comment.
Fixes #220

feat(popover): support templates

---

src/modal/docs/demo.html
src/modal/docs/demo.js
src/modal/docs/readme.md
src/modal/modal.js
src/modal/test/modal.spec.js
template/modal/backdrop.html
template/modal/window.html

Add ability to disable animations. Built on top of #2724 .

feat(modal): add option to disable animations

---

src/modal/modal.js

XHTML does not allow empty attributes
Produces errors like  
`
Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
`

make it useable in xhtml documents

---

src/datepicker/datepicker.js
src/datepicker/test/datepicker.spec.js

fix(datepicker): datepicker-popup compatibility with ngModelOptions

---

src/modal/modal.js
src/modal/test/modal.spec.js
template/modal/window.html

- supports Angular 1.4
Fixes #3787
Fixes #3806
Fixes #3873
Closes #3888

fix(modal): closing breaks on missing scope, 1.4

---

src/modal/modal.js
src/modal/test/modal.spec.js
template/modal/backdrop.html

fix(modal): backdrop animation on AngularJS 1.4

---

index.html

Found a typo while browsing through the docs.

Typo: 'rendered' changed to <code>rendered</code>

---

src/popover/test/popover-html.spec.js
src/popover/test/popover-template.spec.js
src/popover/test/popover.spec.js
src/tooltip/test/tooltip-template.spec.js
src/tooltip/test/tooltip.spec.js
src/tooltip/test/tooltip2.spec.js
src/tooltip/tooltip.js

This is a rollup commit intended to address several
issues around the positioning and parsing of
attributes.
- Fixes issue introduced under PR #4311 where setting
height and width in tooltip position function
messed up arrow placement.
- Fixes issue introduced under PR #4363 where setting
visibility to hidden in tooltip position function
caused elements in popover to lose focus.
- Fixes issue #1780 where tooltip would render if
content was just whitespace.
- Fixes issue #3347 where tooltip isolate scope was
being accessed after it was set to null.  Observers
will now be created/destroyed as tooltip opens/closes
which will also offer a performance improvement.
- Fixes issue #3557 by implementing evalAsync to set
tooltip scope isOpen property.
- Fixes issue #4335 where if model isOpen …

refactor(tooltip): rollup commit for several issues

---

src/tooltip/tooltip.js

In the tooltip $$postDigest function a check is done
on ttScope.isOpen but ttScope may have been set to null
in the scope.$on('$destroy'...) function.  Added a
check to make sure ttScope is defined and not null.
Fixes #4552

fix(tooltip): check for ttScope in $$postDigest

---

src/tooltip/tooltip.js

The tooltip was not being removed from the stackedMap
resulting in a memeory leak.  Tooltip will now be
removed from the stackedMap in scope destroy
function.
Fixes #4604

fix(tooltip): clean up stackedMap on scope destroy

---

src/tooltip/tooltip.js

The watch for the isOpen property from the model was not
checking to see if the internal tooltip scope was still
valid (null or undefined) before comparing the value to
the tooltip scope isOpen property.
Closes #4697
Fixes #4683

fix(tooltip): null scope check in isOpen watch

---

misc/demo/index.html

In the download modal on the demo page, changed Bower info to suggest using npm instead.

chore(docs): downloads - promote npm

---

src/popover/docs/demo.html
src/popover/docs/demo.js
src/popover/docs/readme.md
src/position/docs/demo.html
src/position/docs/demo.js
src/position/docs/readme.md
src/position/position.js
src/position/test/position.spec.js
src/tooltip/docs/demo.html
src/tooltip/docs/demo.js
src/tooltip/docs/readme.md
src/tooltip/tooltip.js

Implementing the ability to auto position elements in the position service - positionElements function.  This will allow tooltips and popovers to position where they fit within the closest scrollable ancestor.  As part of this PR I also documented the position service functions and refactored some of the code to make it more readable.  Partially closes #4762.

feat(position): implement auto positioning

---

src/position/position.js

- The element selector was not limited to direct descendants so
nested tooltip/popover arrow elements were getting selected instead
of the direct descendant arrow element.
Fixes #5230

fix(position): positionArrow descendant selector

---

src/position/position.js
src/tooltip/tooltip.css
src/tooltip/tooltip.js

- Move arrow position style overrides to a class instead of inline styles.  This will allow for consumers to position the arrow to suit their needs by setting margins on the arrow element.
- Optimize when the positionTooltip function calls the positionArrow function.  Now the arrow position will only be recalced when the tooltip placement changes.
Fixes #5464
[Plunk](http://plnkr.co/edit/LD4XHjwn1ZaVowSAeALv?p=preview) with changes.

feat(tooltip): arrow position

---

src/position/docs/readme.md
src/position/position.js
src/position/test/position.spec.js

Added a function to check whether an element is scrollable.  This is useful in some positioning operations where the element needs to be checked if it's scrollable before going after the scrollParent.

feat(position): add isScrollable function

---

src/position/position.js

Use the body as the viewport to determine available size for auto position when the target element is append-to-body.
Fixes #5576

fix(position): auto position append to body

---

src/popover/popover.js
src/popover/test/popover-html.spec.js
src/popover/test/popover-template.spec.js
src/popover/test/popover.spec.js
src/tooltip/tooltip.js
template/popover/popover-html.html
template/popover/popover-template.html
template/popover/popover.html

Using an attribute of title on the tooltip template was causing the browser tooltip to display.
Fixes: #5719

fix(popover): rename title attribute

---

src/modal/modal.js

Check if appendToElement has scrolling disabled before adding
the scrollbar padding.
Fixes #6037

fix(modal): check for overflow hidden

---

src/dropdown/docs/readme.md
src/dropdown/dropdown.js
src/dropdown/test/dropdown.spec.js

Make dropdown-append-to-body accept a value which will be evaluated to
determine if the menu should be appended to body. If no value is
specified, or a non-false value is specified then the menu will be
appended to body. If the value is `false` then the menu will not be
appended to body.

feat(dropdown): make dropdown-append-to-body configurable
